feat: QnA import url
microsoft/BotFramework-Composer pull request #3919
Opened 2020-08-27 08:29 UTC by zhixzhan

## Description
QnA import from url will create <name>.source.qna, 
```
> !# @source.urls = <urls>
> !# @source.name = <name>
```

For dialog.qna import by
```
[import](<name>.source.qna)
```

All up view can edit all imported qna file.

## Task Item
#minor

## Screenshots
<img width="914" alt="image" src="https://user-images.githubusercontent.com/49866537/91416728-62d8f680-e882-11ea-9d32-b34b98a8bf0a.png">

<img width="912" alt="image" src="https://user-images.githubusercontent.com/49866537/91416693-58b6f800-e882-11ea-9a96-822f3143942c.png">

2020-08-27 08:35 UTC, zhixzhan commented
To use customize resolver, this PR is base on https://github.com/microsoft/BotFramework-Composer/pull/3778 doing qna import

2020-09-01 02:41 UTC, boydc2014 commented
A few things in technical side
1. let's use [import](faq.source.qna) instead of "[faq](faq.source.qna)". The latter approach also works, but brings more efforts to maintain. 
2. source.name is not needed in the options, because the file name indicates the source name.

2020-09-30 18:02 UTC, hatpick requested changes

2020-09-30 18:02 UTC, hatpick commented on Composer/packages/server/src/models/bot/botProject.ts
> +      // throw new Error(`no such file ${name}`);
remove commented

2020-09-30 18:02 UTC, hatpick commented on Composer/packages/server/src/models/bot/builder.ts
>      // if (config.models.length === 0) {
remove commented

2020-10-09 06:29 UTC, zhixzhan commented on Composer/packages/client/src/components/EditableField.tsx
> +  onChange: (newValue?: string) => void;
It's inherit from fluentUI TextField:
```onChange: (e, newValue?: string)```

2020-10-09 06:47 UTC, zhixzhan commented on Composer/packages/client/src/components/EditableField.tsx
>    }, [value]);
I guess not, here is sync external value change, internal change suppose to be not trigger this.

2020-10-13 04:40 UTC, zhixzhan commented on Composer/packages/client/src/recoilModel/types.ts
> +export enum NotificationCardTypes {
I thought the Notification types are enum, here set to enum type can strict created notifications to be supported types. @lei9444 do you think this change valid ?

2020-10-13 06:57 UTC, zhixzhan commented on Composer/packages/client/src/recoilModel/types.ts
> +export enum NotificationCardTypes {
Offline talked to leilei, I see the diffrence

2020-10-15 16:25 UTC, cwhitten approved these changes

2020-10-15 16:26 UTC, merged