Settings page
microsoft/BotFramework-Composer pull request #4456
Opened 2020-10-21 13:00 UTC by liweitian

## Description

## Task Item
Closes #3962 

## Screenshots

2020-10-21 18:24 UTC, hatpick submitted a review, later dismissed
Early feedback

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +const TableView: React.FC<BotProjectSettingsProps> = (props) => {
give it a better name to represent what it's doing:
e.g., ```BotSettingsTableView```

whatever name you give, please change the file name to that.

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +    children: {},
default should be null right?

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +  // const [isluisKeyComponentDisabled, setLuisKeyComponentDisabled] = useState<boolean>(!isRootBot && !skillLuisKey);
remove commented

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +    children: {},
null?

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +  const [errorsMsg, setErrorsMsg] = useState<ErrorMsg>({});
why empty {} instead of nothing (undefined) or null?

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +import { Dialog, DialogType } from 'office-ui-fabric-react/lib/Dialog';
use DialogWrapper from @bfc/ui-shared

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +      const targets = (publishTargets || []).concat([
nit: ```[...(publishTargets  || []), {
          name,
          type,
          configuration,
        }]```

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +    [publishTargets, projectId, botName]
why botName dep?

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +    [publishTargets, projectId, botName, editTarget]
why botName dep?

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +  }, [projectId]);
skillHostEndpoint missing?

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +  const AppIdOrPassWord = useMemo(() => {
Password vs. PassWord

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +                  MicrosoftAppId: formatMessage('Microsoft App Id is needed'),
App Id  => AppId

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +          onChange={async (e, value) => {
please define this outside, it's too big of a callback to have inline

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +  const AppIdOrPassWord = useMemo(() => {
Maybe make this it's own component instead of using useMemo?
you can use React.memo on the new component to prevent excessive renders

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +          onChange={async (e, value) => {
too big, please extract

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +  const ExternalService = useMemo(() => {
Please extract to a component

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/table-view.tsx
> +// Licensed under the MIT License.
This is a huge component, I was going through to comment but there are some repetitive comments, please break down this big component to the smaller component and compose them together in the TableView.

2020-10-21 18:24 UTC, hatpick commented on Composer/packages/lib/shared/src/constant.ts
>  export const SensitiveProperties = [
remove commented code if not needed

2020-10-29 08:15 UTC, liweitian commented on Composer/packages/client/src/pages/botProject/runtime-settings/RuntimeSettings.tsx
> +  }, []);
@benbrown Could you have a look on this? I am not quite sure about this functionality.

2020-10-29 08:15 UTC, liweitian commented on Composer/packages/client/src/pages/botProject/runtime-settings/RuntimeSettings.tsx
> +    setNeedsUpdate(boilerplateVersion.updateRequired || false);
@benbrown Could you have a look on this? I am not quite sure about this functionality.

2020-10-29 18:28 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
> +          {isAdvancedSettingsEnabled && (
isAdvancedSettingsEnabled ? render this : render that

2020-10-29 18:28 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/BotProjectSettingsTableView.tsx
> +  hasSkills: boolean;
Shouldn't it be optional since you gave it default value on L#27

2020-10-29 18:28 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/BotProjectSettingsTableView.tsx
> +// Copyright (c) Microsoft Corporation.
This now looks much nicer, great job breaking it down into smaller components 👍

2020-10-29 18:28 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/ExternalService.tsx
> +    return isDefault && luFile?.content;
Maybe use ```!!(isDefault && luFile?.content)``` to force a boolean value

2020-10-29 18:28 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/ExternalService.tsx
> +            onChange={async (e, value) => {
please create a callback, it got big

2020-10-29 18:28 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/ExternalService.tsx
> +        {!isRootBot && (
```isRootBot ? this : that```

2020-10-29 18:28 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/PublishTargets.tsx
> +import { Dialog, DialogType } from 'office-ui-fabric-react/lib/Dialog';
Have you considered using DialogWrapper from ui-shared

2020-10-29 18:28 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/PublishTargets.tsx
> +  const onEdit = async (index: number, item: PublishTarget) => {
this can benefit from useCallback as well

2020-10-29 18:28 UTC, hatpick commented on Composer/packages/client/src/pages/botProject/PublishTargets.tsx
> +          targets={(publishTargets || []).filter((item) => editTarget && item.name != editTarget.item.name)}
!==

2020-10-29 19:21 UTC, benbrown commented on Composer/packages/client/src/pages/botProject/runtime-settings/RuntimeSettings.tsx
> +  }, []);
This is testing to see if the "boilerplate" material, including the provisioning scripts, is out of date and needs an update.  If true, it displays an extra box on the runtime settings page offering the ability to automatically update these files.

2020-10-29 19:24 UTC, benbrown commented on Composer/packages/client/src/pages/botProject/runtime-settings/RuntimeSettings.tsx
> +    setNeedsUpdate(boilerplateVersion.updateRequired || false);
|| false not strictly needed

2020-11-02 08:24 UTC, liweitian commented on Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
> +    navigateTo(`/bot/${rootBotProjectId}/botProjectsSettings/root`);
it is asynchrous. Changed it to: 
if (!botProject) {
    navigateTo(`/bot/${rootBotProjectId}/botProjectsSettings/root`);
    return null;
}

2020-11-02 11:05 UTC, liweitian commented on Composer/packages/client/src/pages/botProject/BotProjectSettings.tsx
> +      console.error(err.message);
@benbrown I am not sure about this. Could you have a look?

2020-11-02 20:08 UTC, srinaath commented
@liweitian Great work on this.

A few comments on this PR. We need to get this rebased with the latest updates on main for me to test the functionality as a whole as I dont know if the bugs that are showing up are because of main or in ur branch. Some of the bugs I see are 

1.  When i try to open the advanced view of a skill I keep getting this error 

![](https://user-images.githubusercontent.com/13004779/97913133-c0664500-1d02-11eb-9938-de8cabf87220.png)

2\. This is a weird bug. The MsAppID and password seem to be ported over to the skill from the Root Bot. This should be avoided. Even though the MsAppId is ported i dont see the appsettings.json of the skill being updated.

2020-11-12 05:11 UTC, srinaath requested changes

2020-11-12 05:11 UTC, srinaath commented on Composer/packages/client/__tests__/pages/botProjectsSettings/AppIdAndPassword.test.tsx
> +// Licensed under the MIT License.
@liweitian

The following are some things Im seeing in this branch.

1.  Create a root bot and add two skills to it. Update the LUIS subscription key or Qna subscription key on the root bot.

*   Expected: When i start any of the skills, the luis or qna config  needs to be populated with the LUIS key from the root bot
*   Actual: The LUIS/ Qna key is updated only on the root bot. Its not progressed to the skill

2\. With the latest SDK runtime, Microsoft AppId and Microsoft App Password are not required to call skills anymore. We can safely remove the styles. The error ribbon needs to appear for missing LUIS key or QNA key if the bot needs those two configs. Currently those errors dont show up.

2020-11-13 00:39 UTC, srinaath commented on Composer/packages/client/src/router.tsx
> +  const botProjectsMetaData = useRecoilValue(botProjectSpaceSelector);
nit: Maybe name this botProjectSpaceData? since that selector gives way more than the metadata of the bots.

2020-11-15 07:51 UTC, srinaath submitted a review, later dismissed

2020-11-16 13:44 UTC, boydc2014 approved these changes

2020-11-16 14:03 UTC, merged