fix: e2e test failed
microsoft/BotFramework-Composer pull request #4898
Opened 2020-11-19 15:53 UTC by lei9444

## Description
![image](https://user-images.githubusercontent.com/39758135/99689603-27854700-2ac2-11eb-9980-1b11b5d743b6.png)
The data collection dialog should be closed when run e2e test

## Task Item
#minor

## Screenshots

2020-11-19 16:37 UTC, a-b-r-o-w-n requested changes
This is a fine thing to do, but here are a couple of questions:

1. Can we just disable this altogether when not in production?
2. If not, is there an api we can interact with during set up that allows us to bypass interacting with the ui?
3. I don't think this is the right place to put this code since it probably only happens on a new user session. It doesn't have anything to do with creating a bot. It should go in a set up function.

@tdurnford do you have any thoughts about the first 2 questions?

2020-11-19 16:37 UTC, a-b-r-o-w-n commented on Composer/cypress/support/commands.ts
> +  });
nit:

```ts
if (cy.findByTestId('data collection dialog')) {
  // ...
}
```

2020-11-19 16:37 UTC, a-b-r-o-w-n commented on Composer/packages/client/src/components/DataCollectionDialog.tsx
> +      data-testid="data collection dialog"
nit: camel case this.

2020-11-19 18:20 UTC, hatpick commented
I'm with @a-b-r-o-w-n on disabling it when not in production.

2020-11-19 19:11 UTC, tdurnford commented
@sorgh @a-b-r-o-w-n I think disabling it when it's not in production is probably the best approach.

2020-11-19 19:32 UTC, a-b-r-o-w-n commented
@tdurnford Something to consider is if we run the e2e tests with a prod build or not. I don't recall.

2020-11-19 20:41 UTC, tdurnford commented
@a-b-r-o-w-n We run it with a production build. I'm trying to set `allowDataCollection` to false in the `Composer/cypress/__e2e_data.json`, but I'm running into issues with that at the moment.

2020-11-20 00:55 UTC, lei9444 commented
this will be fixed in #4907 .
close this

2020-11-20 00:55 UTC, closed without merging