fix: project tree show incorrect imports
microsoft/BotFramework-Composer pull request #5361
Opened 2020-12-17 06:21 UTC by zhixzhan

## Description
Previous imports info is get from content by RegExp match, that is not accurate when LG body include markdown style text.

Fix it by get imports from LG parser side, same to LU/QnA.

## Task Item
close #5347 

## Screenshots
![image](https://user-images.githubusercontent.com/49866537/102451277-21f43000-4073-11eb-845c-94c1fb7c6b88.png)

2020-12-17 19:16 UTC, beyackle requested changes
This looks like it should work, but I think the type structure needs more clarity.

2020-12-17 19:16 UTC, beyackle commented on Composer/packages/lib/indexers/src/utils/luUtil.ts
> +    ({ Path, Description }) => {
Sections is just defined as `any[]`, so I can't tell if these fields actually exist. Would you mind tracking down the definition for what a "section" actually is and changing it accordingly in `packages/types/src/indexers.ts`? That's where the LuFile and LuParseResource types are defined.

2020-12-17 22:12 UTC, hatpick submitted a review, later dismissed
Looks good to me, thank you.

2020-12-18 18:13 UTC, hatpick approved these changes

2021-01-05 20:47 UTC, hatpick approved these changes

2021-01-08 07:44 UTC, merged