perf: break down the design page
microsoft/BotFramework-Composer pull request #5623
Opened 2021-01-27 12:54 UTC by lei9444

## Description
**In this PR**

This is the first step to break down the design page. This PR just split the design page to four parts, but the states in every component is not optimal. 
![image](https://user-images.githubusercontent.com/39758135/105992486-284ce180-60e0-11eb-92cd-4d8fc77401d0.png)

Create this PR to avoid too many conflicts

**Next step**
Optimize every component and states

## Task Item
refs #5559

## Screenshots

2021-01-28 02:00 UTC, GeoffCoxMSFT commented on Composer/packages/client/src/pages/design/Listener.tsx
> +  }, [location]);
Does this need more dependencies like the things this function uses from props?

2021-01-28 02:30 UTC, srinaath commented on Composer/packages/client/src/recoilModel/selectors/dialogs.ts
> +    return get(dialogsSelectorFamily(projectId))[0];
get(dialogsSelectorFamily(projectId))?.\[0\]. Null reference check

2021-01-28 02:33 UTC, srinaath commented on Composer/packages/client/src/pages/design/CommandBar.tsx
> +  const toolbarItems: IToolbarItem[] = [
Can this be memoized?

2021-01-28 02:34 UTC, srinaath commented on Composer/packages/client/src/pages/design/CommandBar.tsx
> +  const toolbarItems: IToolbarItem[] = [
Or do u think its better to get this PR in to get the structure and we can optimize in successive PR's

2021-01-28 18:21 UTC, hatpick requested changes

2021-01-28 18:21 UTC, hatpick commented on Composer/packages/client/src/pages/design/Listener.tsx
> +const Listener: React.FC<RouteComponentProps<{ dialogId: string; projectId: string; skillId?: string }>> = (props) => {
Please pick a better name for this or at least add comments describing the responsibilities of this faceless component.

Even better, consider creating a hook.

2021-01-28 18:21 UTC, hatpick commented on Composer/packages/client/src/pages/design/PropertyPanel.tsx
> +  }, [skills, isSkill]);
skillsByProjectId dep

2021-01-28 18:21 UTC, hatpick commented on Composer/packages/client/src/pages/design/SideBar.tsx
> +      <Modals projectId={projectId} />
I think this belongs to DesignPage not SideBar, what do you think?

2021-01-29 02:17 UTC, lei9444 commented
Thanks @GeoffCoxMSFT  @srinaath @hatpick 
Do you think we can merge this PR first if all checks pass? Then I can do optimize for every single component in successive PR's

2021-01-29 02:21 UTC, srinaath commented
I think it makes sense to get this PR in early. The more we delay more workstreams are going to refactor their code furthur later.

2021-01-29 02:58 UTC, hatpick approved these changes

2021-01-30 01:10 UTC, srinaath approved these changes

2021-02-01 02:33 UTC, merged